services:
  - type: web
    name: vio-app-final
    runtime: buildpacks
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
    buildpacks:
      - url: heroku/python
      - url: https://github.com/heroku/heroku-buildpack-ffmpeg-latest.git